#!/bin/bash

host=`hostname`

if [ ${host:0:3} == "gra" ]
then
	echo running on graham
else
	echo running elsewhere
fi

name=neuroglia_interactive
salloc -J $name  -D `pwd` --time=1:00:00 --cpus-per-task=8 --ntasks=1 --mem=32000 --account=rrg-akhanf  neurogliaShell #singularity shell $SINGULARITY_OPTS $SINGULARITY_IMG $@
